card:
  message: "Welcome to Card UAT Environment"
  owner: "Divya"
  userInfo:
    mail: "{cipher}3fd24bb01406ea826b0f022340119f31c413e3516e366f4ac82f9d70a7f1c354eb2f4f2af80bffa5e0324541edd9549d"
    contact: "8220021216"
  AddressLine[0]: "31, Nattar Street Main"
  AddressLine[1]: "Murungapakkam"
  AddressLine[2]: "Puducherry - 605004"
