card:
  message: "Welcome to Card Dev Environment"
  owner: "Naren"
  userInfo:
    mail: "narendran3678@gmail.com"
    contact: "7092802533"
  AddressLine[0]: "29, Nattar Street Main"
  AddressLine[1]: "Murungapakkam"
  AddressLine[2]: "Puducherry - 605004"