loan:
  message: "Welcome to Loan Dev Environment"
  owner: "Naren"
  userInfo:
    mail: "{cipher}447b7dcdc77a8d13c4bd4cfb83c3a13b09620a28765d4dc3ca74cdb3e3a5bedf5e3be803b74880a9afb41daac2f35bef"
    contact: "6385810492"
  AddressLine[0]: "29, Nattar Street Main"
  AddressLine[1]: "Murungapakkam"
  AddressLine[2]: "Puducherry - 605004"
